const data = {
	"data":{
		"flowStatus":0,
		"flowName":"请假单",
		"user":{
			"sex":1,
			"name":"杨滔",
			"company":"四川东久科技股份有限公司",
			"sn":"0025",
			"avatar":"http://192.168.10.223:7272/image/app/avatar/108.png",
			"department":"软件开发事业部",
			"userId":"108"
		},
		"tableData":[
			{
				"title":"用户ID",
				"type":"hidden",
				"name":"userId",
				"readOnly":true,
				"value":"108"
			},
			{
				"title":"工作流ID",
				"type":"hidden",
				"name":"flowId",
				"readOnly":true,
				"value":"2"
			},
			{
				"title":"工作流实例ID",
				"type":"hidden",
				"name":"flowEntityId",
				"readOnly":true
			},
			{
				"title":"所属公司",
				"type":"radio",
				"name":"data1510889654000",
				"readOnly":false,
				"options":[
					{
						"name":"东久科技",
						"checked":false,
						"value":"1"
					},
					{
						"name":"成冠实业",
						"checked":false,
						"value":"2"
					}
				],
				"text":"所属公司"
			},
			{
				"title":"请假类型",
				"type":"select",
				"name":"data1505874604000",
				"readOnly":false,
				"options":[
					{
						"name":"事假",
						"checked":false,
						"value":"1"
					},
					{
						"name":"病假",
						"checked":false,
						"value":"2"
					},
					{
						"name":"年假",
						"checked":false,
						"value":"3"
					},
					{
						"name":"婚假",
						"checked":false,
						"value":"4"
					},
					{
						"name":"产假",
						"checked":false,
						"value":"5"
					},
					{
						"name":"其他假",
						"checked":false,
						"value":"6"
					},
					{
						"name":"丧假",
						"checked":false,
						"value":"7"
					},
					{
						"name":"陪产假",
						"checked":false,
						"value":"8"
					}
				],
				"text":"请假类型"
			},
			{
				"title":"请假开始日期",
				"type":"date",
				"name":"data1508376575000",
				"readOnly":false
			},
			{
				"title":"请假结束日期",
				"type":"date",
				"name":"data1506318717000",
				"readOnly":false
			},
			{
				"title":"请假天数",
				"type":"text",
				"name":"data1505095824000",
				"readOnly":false
			},
			{
				"title":"请假原因",
				"type":"textarea",
				"name":"data5",
				"readOnly":false
			}
		],
		"isFirstTask":false,
		"handleStatus":"0",
		"currentTaskName":"待保存",
		"isEnd":false
	},
	"message":"获取工作流详情HTML5成功",
	"status":"1",
	"success":true
}

export default data